/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'David' at '9/30/16 12:26 AM' with Gradle 2.14.1
 *
 * @author David, @date 9/30/16 12:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
